%YAML:1.0
---
MAX_BLUR_VALUE: 0
MAX_GAUSS_VALUE: 0
MAX_MEDIAN_VALUE: 0
MAX_BILAT_LENGTH: 0
RES_BLUR_VALUE: 0
RES_GAUSS_VALUE: 0
RES_MEDIAN_VALUE: 0
RES_BILAT_LENGTH: 0
alpha: 0
beta: 255
rangeDispLow: 0
rangeDispHigh: 255
